version: "3.8"
services:

  web-api:
    profiles:
      - all
      - api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
    environment:
      DOTNET_ENVIRONMENT: development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: GRPC
      ConnectionStrings__mongodb: "mongodb://mongodb:27017"
      kafka__bootstrapServers: "kafka:9092"
    depends_on:
      - otel-collector
      - mongodb

  # Data storage
  mongodb:
    image: mongo:6-jammy
    profiles:
      - all
      - datastore
      - local-development
    ports:
      - '27017:27017'
    # A volume could be added here for persistant storage across runs

  # OpenTelemetry services
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    profiles:
      - all
      - opentelemetry
    volumes:
      - ./env/otel-config.yaml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
    environment:
      JAEGER_ENDPOINT: "jaeger:4317"
      LOKI_ENDPOINT: "http://loki:3100/loki/api/v1/push"
    ports:
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
      - "13133:13133" # health_check extension
      - "55679:55679" # ZPages extension
    depends_on:
      - jaeger
      - prometheus
      - loki

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    profiles:
      - all
      - opentelemetry
    ports:
      - "16686:16686" # Jaeger Web UI

  prometheus:
    image: prom/prometheus:v2.42.0
    profiles:
      - all
      - opentelemetry
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.7.4
    profiles:
      - all
      - opentelemetry
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:9.4.3
    profiles:
      - all
      - opentelemetry
    volumes:
      - ./env/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
